[package]
name = "dex_utils"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
dex_utils = "0x42cd8467b1c86e59bf319e5664a09b6b5840bb3fac64f5ce690b5041c530565a"
vip = "0xe55cc823efb411bed5eed25aca5277229a54c62ab3769005f86cc44bc0c0e5ab"
vesting = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "v1.0.0" }
vip = { git = "https://github.com/initia-labs/vip-contract.git", subdir = "", rev = "main" }