[package]
name = "dex_utils"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
dex_utils = "0x2"
vip = "0x3"
vesting = "0x4"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "v1.0.0" }
vip = { git = "https://github.com/initia-labs/vip-contract.git", subdir = "", rev = "main" }