[package]
name = "dex_utils"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
dex_utils = "0x589B1E861579C3F07092859DB5F8963E1DAC50F1"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "47297f0e4fa0e259d509daafc09a9790da1e95fe" }
