[package]
name = "minitswap-router"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
router = "0x42cd8467b1c86e59bf319e5664a09b6b5840bb3fac64f5ce690b5041c530565a"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "7f413c5e84fe9929c5b0e87c7abe29e2ec936514" }