[package]
name = "minitswap-router"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
router = "0x42cd8467b1c86e59bf319e5664a09b6b5840bb3fac64f5ce690b5041c530565a"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "1d785b1fab4d2cf8dec19f7e513c7f5b56c98fdd" }