[package]
name = "nft-transfer"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
nft_transfer = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }