[package]
name = "math"
version = "0.0.1"

[addresses]
std = "0x1"
math = "_"

[dev-addresses]
math = "0x2"

[dependencies]
MoveStdlib = { git = "https://github.com/initia-labs/initiavm.git", subdir = "crates/stdlib/src/move_stdlib", rev = "27a15df58f6587dc6335a21ef601bfcb11b59e04"  }
MoveNursery = { git = "https://github.com/initia-labs/initiavm.git", subdir = "crates/stdlib/src/move_nursery", rev = "27a15df58f6587dc6335a21ef601bfcb11b59e04" }
InitiaStdlib = { git = "https://github.com/initia-labs/initiavm.git", subdir = "crates/stdlib/src/initia_stdlib", rev = "27a15df58f6587dc6335a21ef601bfcb11b59e04" }

