[package]
name = "swap-transfer"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
swap_transfer = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"
dex_utils = "0x589b1e861579c3f07092859db5f8963e1dac50f1"
me ="0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"

[dependencies]
InitiaStdlib = { local = "../../../backends/initiavm/precompile/modules/initia_stdlib" }
dex_utils = { local = "../dex-utils" }