[package]
name = "launch"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
launch = "_"

[dev-addresses]
launch = "0x2"

[dependencies]
InitiaStdlib = { local = "../../../backends/initiavm/precompile/modules/initia_stdlib" }
