[package]
name = "launch"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
launch = "0x7DE0DE4F4A289EC455F0EB4A496DFA3DBAE3A375"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "precompile/modules/initia_stdlib", rev = "47297f0e4fa0e259d509daafc09a9790da1e95fe" }
