[package]
name = "launch"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
launch = "0x7DE0DE4F4A289EC455F0EB4A496DFA3DBAE3A375"

[dev-addresses]
launch = "0x2"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/testnet.git", subdir = "stone-11/move/initia_stdlib", rev = "d3debed2d4aeb8ba1eb9635f5987e0c08455dc6c" }
