[package]
name = "launch"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
launch = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"

[dev-addresses]
launch = "0x2"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/testnet.git", subdir = "stone-11/move/initia_stdlib", rev = "162138c277040eaca8a4d5f7ba4d8ec13ad80a4a"  }
