[package]
name = "launch"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
launch = "0xfa5f07319724580ef16dcef6ce4d3b0bd0348e48"

[dev-addresses]
launch = "0x2"

[dependencies]
InitiaStdlib = { local = "../../../backends/initiavm/precompile/modules/initia_stdlib" }
MoveStdlib = { local = "../../../backends/initiavm/precompile/modules/move_stdlib" }
MoveNursery = { local = "../../../backends/initiavm/precompile/modules/move_nursery" }
