[package]
name = "dex"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
dex = "_"
dex_util = "_"

[dev-addresses]
dex = "0x3"
dex_util = "0x4"

[dependencies]
InitiaStdlib = { local = "../../initiavm/crates/stdlib/src/initia_stdlib" }
MoveStdlib = { local = "../../initiavm/crates/stdlib/src/move_stdlib" }
MoveNursery = { local = "../../initiavm/crates/stdlib/src/move_nursery" }
